/*1. Declare uma variável de nome weight
let weight
*/

/*2. Que tipo de dado é a variável acima?
console.log(typeof weight)
/*

/*3. Declare uma variável e atribua valores para cada um dos dados:
    *name: String
    *age: Number (integer)
    *stars: Number(float)
    *isSubscribed: Boolean

let name, age, stars, isSubscribed
    name = "Eduardo"
    age = 20
    stars = 50.5
    isSubscribed = true
*/

/*4. A variável student abaixo é de que tipo de dados?
let student = {};
console.log(typeof student)
*/

//4.1 Atribua a ela as mesmas propriedades e valores do exercício 3.
/*let student = {
    name: "Eduardo Luiz",
    age: 20,
    stars: 4.9,
    isSubscribed: true,
}
console.log(student)*/


//4.2 Mostre no console a seguinte mensagem:
//<name> de idade <age> pesa <weight> kg.
//let student = {
//    name: "Eduardo",
//    age: 20,
//    stars: 5,
//    isSubscribed: true,
//    weight: 74.5,
//}
//console.log(`${student.name} de idade ${student.age} pesa ${student.weight}.`)
//console.log(student)


/*5. Declare uma variável do tipo Array, de nome students e atribua a ela nenhum valor, ou seja, somente o array vazio.
let students = []
*/

/*6. Reatribua valor para a variável acima, colocando dentro dela o objeto student da questão 4. (Não copiar e colar o objeto, mas usar o objeto criado e 
inserir ele no array)*/
//students = [
//    student
//]
///console.log(students)

/*7. Coloque no console o valor da posição zero do Array acima*/
//console.log(students[0])
//console.log(students[0])
/*8. criei um novo student e coloque na posição 1 do Array students*/
/*const john = {
    name: "john",
    age: 25,
    weight: 89.6
    isSubscribed: true
}
students = [
    student,
    john
]*/